# Generated by Django 4.2.7 on 2024-03-11 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("www_uz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="websites", to="www_uz.subcategory"
            ),
        ),
    ]
