# Generated by Django 4.2.7 on 2024-03-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www_uz", "0002_alter_website_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="joined_date",
            field=models.DateTimeField(),
        ),
    ]
