# Generated by Django 4.2.7 on 2024-03-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www_uz", "0003_alter_visitor_joined_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="joined_date",
            field=models.DateField(),
        ),
    ]
